image: node:latest

before_script:
  - npm i -g gulp-cli
  - npm install

cache:
  paths:
  - node_modules/

pages:
  script:
   - gulp release
  artifacts:
    paths:
    - public
  only:
    - master
